import Link from "next/link";
import { notFound } from "next/navigation";
import { entryGuides, findEntryGuide, guidePublished } from "@/lib/entry-guides";
import { SITE_URL } from "@/lib/site";
import "../start.css";
export function generateStaticParams() { return entryGuides.map(g => ({ slug: g.slug })); }
export async function generateMetadata({ params }: { params: Promise<{slug: string}> }) { const { slug } = await params; const g = findEntryGuide(slug); if (!g) return {}; return { title: g.title, description: g.description, alternates: { canonical: `${SITE_URL}/start/${g.slug}` }, openGraph: { title: g.title, description: g.description, url: `${SITE_URL}/start/${g.slug}`, type: "article", publishedTime: guidePublished } }; }
export default async function GuidePage({ params }: { params: Promise<{slug: string}> }) {
 const { slug } = await params, g = findEntryGuide(slug); if (!g) notFound(); const next = findEntryGuide(g.next)!;
 const schema = { "@context": "https://schema.org", "@type": "Article", headline: g.title, description: g.description, datePublished: guidePublished, author: { "@type": "Organization", name: "BYNV", url: SITE_URL }, mainEntityOfPage: `${SITE_URL}/start/${g.slug}` };
 return <article className="container start-guides start-article"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><nav aria-label="Breadcrumb"><Link href="/start">Practical starting points</Link></nav><header><p className="eyebrow">BYNV · Original practical guide</p><h1>{g.title}</h1><p className="lede">{g.intro}</p><p className="start-byline">By BYNV · <time dateTime={guidePublished}>September 17, 2026</time> · Written with AI assistance</p></header><aside className="start-exercise"><p className="eyebrow">Try this now</p><h2>One useful move</h2><p>{g.exercise}</p></aside>{g.sections.map(s => <section key={s.title}><h2>{s.title}</h2>{s.paragraphs.map(p => <p key={p}>{p}</p>)}</section>)}<section><h2>{g.question}</h2><p>{g.answer}</p></section><aside><h2>Connect your next step to a bigger picture.</h2><p>Take the free Version Snapshot for a starting reflection. Kai helps explain your result, and you can create an account to continue into a personal plan.</p><Link className="button" href="/assessment">Take my free Version Snapshot</Link><p className="start-byline">A reflection tool, not a diagnosis or a promise of results.</p></aside><footer><p>Another useful guide: <Link href={`/start/${next.slug}`}>{next.title}</Link></p><p>Already a member? <Link href="/next-version-reset">Talk through your next move with Guided Kai.</Link></p></footer></article>;
}
