import { Button, CTA, Eyebrow, JsonLd, SectionTitle } from "@/components/ui";
import { pillars, resources } from "@/lib/data";
import Link from "next/link";
export default function Home() { return <>
  <JsonLd data={{ "@context": "https://schema.org", "@type": "WebSite", name: "BYNV", url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000" }} />
  <section className="hero"><div className="container hero-grid"><div><Eyebrow>Become Your Next Version</Eyebrow><h1>Don’t find yourself.<br/><em>Design yourself.</em></h1><p className="lede">A deliberate system for seeing where you are, choosing where you’re going and building the person your next chapter requires.</p><div className="button-row"><Button href="/assessment">Take your Version Snapshot</Button><Button href="/framework" secondary>Explore the method</Button></div><p className="micro">Free · 3 minutes · No account required</p></div><div className="hero-orbit" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="monogram">V<span>∞</span></div><p>Clarity<br/>Direction<br/>Momentum</p></div></div></section>
  <section className="manifesto container"><p>Most people wait for change.</p><h2>The Architects <em>build it.</em></h2><p>BYNV is a personal growth system and member community for people who want to understand where they are, choose what matters next, and turn intention into repeatable action. It is not a quick fix or borrowed motivation.</p></section>
  <section className="section container"><SectionTitle eyebrow="The Architect Method" title="Your growth deserves a blueprint." copy="A grounded cycle for moving from awareness to aligned action—then doing it again, wiser."/><div className="pillar-grid">{pillars.map((p) => <article key={p.number}><span>{p.number}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div><Button href="/framework" secondary>How the method works</Button></section>
  <section className="split-section"><div className="container split"><div className="score-preview"><span>Your Version Snapshot</span><strong>72</strong><div/><small>A preliminary signal</small></div><div><Eyebrow>Begin with awareness</Eyebrow><h2>Know the version you’re starting from.</h2><p>The free six-question Version Snapshot turns your reflections into a preliminary Version Score, a focus area and three practical next steps before the deeper Architect Assessment.</p><ul className="tick-list"><li>A Snapshot across six areas</li><li>A clear first focus</li><li>A simple seven-day action plan</li></ul><Button href="/assessment">Take the free Snapshot</Button></div></div></section>
  <section className="section container"><SectionTitle eyebrow="What happens after signup" title="A system worth returning to." copy="Complete the deeper Architect Assessment, open your Blueprint, choose a Daily Focus, build goals and cycles, join Challenges, reflect privately, and use AI deliberately instead of doing everything yourself."/><div className="cards"><article className="card"><p className="eyebrow">Understand</p><h3>Assessment + Blueprint</h3><p>Your 42-question member assessment establishes a fuller Version Score across seven domains and turns it into a focused starting plan.</p></article><article className="card"><p className="eyebrow">Practice</p><h3>Daily OS + AI leverage</h3><p>Turn priorities into action, identify repeatable work AI can help carry, and keep human judgment responsible for context, verification, and decisions.</p></article><article className="card"><p className="eyebrow">Belong</p><h3>Kai + Community</h3><p>Kai connects permitted private context to the next useful action—and can teach a transferable AI workflow—while member Rooms support accountability and shared Challenges.</p></article></div><Button href="/membership" secondary>Compare membership</Button></section>
  <section className="section container"><SectionTitle eyebrow="Free Architect resources" title="Useful tools for a life under construction." copy="Download practical BYNV worksheets you can use today—no account required."/><div className="resource-grid">{resources.map((r) => <Link href={`/resources#${r.slug}`} key={r.slug}><span>{r.tag} · {r.read}</span><h3>{r.title}</h3><p>{r.summary}</p><b>Open resource →</b></Link>)}</div></section><CTA />
  </> }
