import { Button, CTA, Eyebrow, JsonLd, SectionTitle } from "@/components/ui";
import { pillars, resources } from "@/lib/data";
import Link from "next/link";
export default function Home() { return <>
  <JsonLd data={{ "@context": "https://schema.org", "@type": "WebSite", name: "BYNV", url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000" }} />
  <section className="hero"><div className="container hero-grid"><div><Eyebrow>Become Your Next Version</Eyebrow><h1>Don’t find yourself.<br/><em>Design yourself.</em></h1><p className="lede">A deliberate system for seeing where you are, choosing where you’re going and building the person your next chapter requires.</p><div className="button-row"><Button href="/assessment">Discover your Version Score</Button><Button href="/framework" secondary>Explore the method</Button></div><p className="micro">Free · 3 minutes · No account required</p></div><div className="hero-orbit" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="monogram">V<span>∞</span></div><p>Clarity<br/>Direction<br/>Momentum</p></div></div></section>
  <section className="manifesto container"><p>Most people wait for change.</p><h2>The Architects <em>build it.</em></h2><p>BYNV is a place for people who refuse to leave their evolution to chance. Not a quick fix. Not borrowed motivation. A practice of becoming—with intention.</p></section>
  <section className="section container"><SectionTitle eyebrow="The Architect Method" title="Your growth deserves a blueprint." copy="A grounded cycle for moving from awareness to aligned action—then doing it again, wiser."/><div className="pillar-grid">{pillars.map((p) => <article key={p.number}><span>{p.number}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div><Button href="/framework" secondary>How the method works</Button></section>
  <section className="split-section"><div className="container split"><div className="score-preview"><span>Your Version Score</span><strong>72</strong><div/><small>Momentum is building</small></div><div><Eyebrow>Begin with awareness</Eyebrow><h2>Know the version you’re starting from.</h2><p>The free assessment turns your own reflections into an indicative Version Score, a focus area and three practical next steps.</p><ul className="tick-list"><li>A snapshot across six areas</li><li>A personalised focus for this season</li><li>A simple seven-day action plan</li></ul><Button href="/assessment">Take the assessment</Button></div></div></section>
  <section className="section container"><SectionTitle eyebrow="From the journal" title="Ideas for a life under construction."/><div className="resource-grid">{resources.map((r) => <Link href="/journal" key={r.slug}><span>{r.tag} · {r.read}</span><h3>{r.title}</h3><p>{r.summary}</p><b>Read reflection →</b></Link>)}</div></section><CTA />
  </> }
