import { Button, CTA, Eyebrow, JsonLd, SectionTitle } from "@/components/ui";
import { pillars, resources } from "@/lib/data";
import Link from "next/link";
import { SITE_URL } from "@/lib/site";
export default function Home() { return <>
  <JsonLd data={{ "@context": "https://schema.org", "@type": "WebSite", name: "BYNV", alternateName: "Become Your Next Version", url: SITE_URL }} />
  <section className="hero"><div className="container hero-grid"><div><Eyebrow>Become Your Next Version</Eyebrow><h1>Don’t find yourself.<br/><em>Design yourself.</em></h1><p className="lede">A practical system for understanding where you are, choosing where you want to go, and turning meaningful goals into real progress.</p><div className="button-row"><Button href="/assessment">Take your Version Snapshot</Button><Button href="/framework" secondary>Explore the method</Button></div><p className="micro">Free · 3 minutes · No account required</p></div><div className="hero-orbit" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="monogram">V<span>∞</span></div><p>Clarity<br/>Direction<br/>Momentum</p></div></div></section>
  <section className="manifesto container"><p>Most people wait for change.</p><h2>The Architects <em>build it.</em></h2><p>BYNV is a personal growth system and member community for people who want to understand where they are, choose what matters next, and turn intention into repeatable action. It is not a quick fix or borrowed motivation.</p></section>
  <section className="section container"><SectionTitle eyebrow="The Architect Method" title="A simple system for building your next version." copy="Four repeatable steps for understanding where you are, choosing a direction, taking action, and learning as you go."/><div className="pillar-grid">{pillars.map((p) => <article key={p.number}><span>{p.number}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div><Button href="/framework" secondary>How the method works</Button></section>
  <section className="split-section"><div className="container split"><div className="score-preview"><span>Your Version Snapshot</span><strong>72</strong><div/><small>Your starting point</small></div><div><Eyebrow>Start with honesty</Eyebrow><h2>Know where you’re starting.</h2><p>The free six-question Version Snapshot gives you a starting Version Score, one area to focus on, and three practical next steps before the deeper Architect Assessment.</p><ul className="tick-list"><li>A Snapshot across six areas</li><li>A clear first focus</li><li>A simple seven-day action plan</li></ul><Button href="/assessment">Take the free Snapshot</Button></div></div></section>
  <section className="section container"><SectionTitle eyebrow="What happens after signup" title="A system worth returning to." copy="Complete your Architect Assessment, open your Blueprint, choose a Daily Focus, build goals, join Challenges, reflect privately, and use AI as a useful tool—not a replacement for your judgment."/><div className="cards"><article className="card"><p className="eyebrow">Understand</p><h3>Assessment + Blueprint</h3><p>Your 42-question member assessment builds a fuller Version Score across seven areas of life and turns it into a focused starting plan.</p></article><article className="card"><p className="eyebrow">Practice</p><h3>Daily OS + AI tools</h3><p>Turn priorities into action, identify work AI can help with, and keep control of your context, decisions, and final results.</p></article><article className="card"><p className="eyebrow">Belong</p><h3>Kai + Community</h3><p>Kai connects your saved BYNV progress to a useful next action, while member Rooms provide accountability, shared Challenges, and support.</p></article></div><Button href="/membership" secondary>Compare membership</Button></section>
  <section className="section container"><SectionTitle eyebrow="Free Architect resources" title="Useful tools for a life under construction." copy="Download practical BYNV worksheets you can use today—no account required."/><div className="resource-grid">{resources.map((r) => <Link href={`/resources#${r.slug}`} key={r.slug}><span>{r.tag} · {r.read}</span><h3>{r.title}</h3><p>{r.summary}</p><b>Open resource →</b></Link>)}</div></section><CTA />
  </> }
