"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Cycle = { id: string; starts_on: string; ends_on: string; focus: string; outcome: string | null; status: string };
export function ArchitectCycle() {
  const [userId, setUserId] = useState(""); const [cycle, setCycle] = useState<Cycle | null>(null); const [message, setMessage] = useState("Loading your cycle…");
  async function load() { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; setUserId(user.id); const { data } = await supabase.from("architect_cycles").select("id,starts_on,ends_on,focus,outcome,status").eq("user_id", user.id).eq("status", "active").order("created_at", { ascending: false }).limit(1).maybeSingle(); setCycle(data); setMessage(""); }
  useEffect(() => { void load(); }, []);
  async function start(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const focus = String(data.get("focus") ?? "").trim(); const days = Number(data.get("days") ?? 30); const start = new Date(); const end = new Date(start); end.setUTCDate(end.getUTCDate() + days - 1); const { error } = await createClient().from("architect_cycles").insert({ user_id: userId, focus, starts_on: start.toISOString().slice(0, 10), ends_on: end.toISOString().slice(0, 10) }); if (error) return setMessage("Your cycle could not be started."); await load(); }
  async function complete(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!cycle) return; const outcome = String(new FormData(event.currentTarget).get("outcome") ?? "").trim(); const { error } = await createClient().from("architect_cycles").update({ status: "completed", outcome: outcome || null }).eq("id", cycle.id).eq("user_id", userId); if (error) return setMessage("Your review could not be saved."); setCycle(null); setMessage("Cycle completed. Your review is preserved."); }
  if (!cycle) return <form className="member-form" onSubmit={start}><label>Cycle focus<input name="focus" required maxLength={240} placeholder="What are you building or strengthening?" /></label><label>Cycle length<select name="days" defaultValue="30"><option value="14">14 days</option><option value="30">30 days</option><option value="60">60 days</option></select></label><button className="button">Begin this Architect Cycle</button><p className="form-message" role="status">{message}</p></form>;
  const today = new Date().toISOString().slice(0, 10); const total = Math.max(1, (Date.parse(cycle.ends_on) - Date.parse(cycle.starts_on)) / 86400000 + 1); const elapsed = Math.min(total, Math.max(1, (Date.parse(today) - Date.parse(cycle.starts_on)) / 86400000 + 1)); const percent = Math.round((elapsed / total) * 100);
  return <section className="cycle-card"><p className="eyebrow">Active Architect Cycle</p><h2>{cycle.focus}</h2><p>{new Date(`${cycle.starts_on}T00:00:00`).toLocaleDateString()} — {new Date(`${cycle.ends_on}T00:00:00`).toLocaleDateString()}</p><div className="architect-progress" aria-label={`${percent}% through this cycle`}><span style={{ width: `${percent}%` }} /></div><p className="progress-copy">Day {Math.round(elapsed)} of {Math.round(total)}</p><form className="member-form" onSubmit={complete}><label>Cycle review<textarea name="outcome" rows={6} maxLength={3000} placeholder="What changed? What worked? What will you carry into the next cycle?" /></label><button className="button">Complete and save review</button><p className="form-message" role="status">{message}</p></form></section>;
}
