"use client";
import { useState } from "react";
import Link from "next/link";
import { canAdvanceCoachingQA, coachingSteps } from "@/lib/coaching-qa";
export function CoachingQA() {
  const [step, setStep] = useState(0); const [request, setRequest] = useState(""); const [preparation, setPreparation] = useState(""); const [notes, setNotes] = useState(""); const [commitment, setCommitment] = useState(""); const [preference, setPreference] = useState("Weekday evening"); const [reviewed, setReviewed] = useState(false);
  return <section className="container coaching-qa"><p className="journey-milestone">SIMULATION ONLY · Browser-session draft · Refreshing or leaving resets this rehearsal. Use fictional practice content.</p><ol className="coaching-steps" aria-label="Coaching rehearsal steps">{coachingSteps.map((name,index)=><li aria-current={step === index ? "step" : undefined} key={name}>{index+1}. {name}</li>)}</ol><article className="panel member-form"><p className="eyebrow">Step {step+1} of {coachingSteps.length}</p><h2>{coachingSteps[step]}</h2>
    {step === 0 && <><h3>Personal review. Clear commitments. Follow-through.</h3><p>The intended experience adds human-led goal review and accountability to the Architect tools. Before selling it, BYNV must define session frequency, length, provider qualifications, response times, cancellation terms, and capacity.</p><p>Coaching is not therapy, emergency support, or medical, financial, or legal advice. Kai is not a human coach.</p></>}
    {step === 1 && <><label>What would you like coaching to help you work on?<textarea value={request} maxLength={1000} onChange={event=>setRequest(event.target.value)} placeholder="QA example: turn a career goal into a manageable weekly plan." /></label><p>No request is sent to a coach. The next screen rehearses the scheduling handoff.</p></>}
    {step === 2 && <><h3>Real scheduling is not available yet.</h3><p>No coach or live calendar is connected. This step captures a practice preference only; it does not reserve a time.</p><label>Practice availability preference<select value={preference} onChange={event=>setPreference(event.target.value)}><option>Weekday evening</option><option>Weekday morning</option><option>Weekend</option></select></label><p className="field-help">Commercial blocker: qualified provider, time-zone-aware calendar, capacity, confirmations, cancellation/rescheduling policy, and agreed service terms.</p></>}
    {step === 3 && <><p>Practice request: {request}</p><p>Preference: {preference} · No appointment booked</p><label>Session preparation<textarea value={preparation} maxLength={2000} onChange={event=>setPreparation(event.target.value)} placeholder="What changed, what is getting in the way, and what would make a session useful?" /></label></>}
    {step === 4 && <><p>This is a simulated session review. No human session has occurred.</p><label>Member-visible practice notes<textarea value={notes} maxLength={2000} onChange={event=>setNotes(event.target.value)} placeholder="Record a useful observation in your own words." /></label><label>One action commitment<textarea value={commitment} maxLength={1000} onChange={event=>setCommitment(event.target.value)} placeholder="What action will you take, and when?" /></label></>}
    {step === 5 && <><h3>Your practice follow-up</h3><p>{notes || "No practice notes entered."}</p><strong>{commitment}</strong><label className="check-row"><input type="checkbox" checked={reviewed} onChange={event=>setReviewed(event.target.checked)} /> Practice commitment reviewed</label><p role="status">{reviewed ? "QA rehearsal complete. No customer record, booking, email, or billing event was created." : "Review the commitment to complete the rehearsal."}</p><Link className="button secondary" href="/daily-focus">Return to my real Daily Focus</Link></>}
    <div className="button-row">{step > 0 && <button className="button secondary" type="button" onClick={()=>setStep(step-1)}>Back</button>}{step < 5 && <button className="button" type="button" disabled={!canAdvanceCoachingQA(step,request,preparation,commitment)} onClick={()=>setStep(step+1)}>{step === 2 ? "Continue simulation — no booking" : "Continue QA rehearsal"}</button>}</div></article></section>;
}
