"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { addDays, entryStatus, entrySteps, loadExperience, momentum, type Experience } from "@/lib/experience";
import { momentumFacts } from "@/lib/momentum";
import { nextExperienceStep } from "@/lib/experience-guidance";
import { cycleProgress } from "@/lib/journey";
import { relevantResources } from "@/lib/library-recommendations";
import { KaiAvatar } from "./kai-avatar";
import { ChangeEvidence, ReviewHistory } from "./change-review";
import "./momentum.css";

export function MomentumOverview({ initial }: { initial: Experience }) {
  const [state,setState]=useState(initial),[error,setError]=useState("");
  useEffect(()=>{let alive=true,version=0;const refresh=()=>{const current=++version;void loadExperience().then(value=>{if(alive&&current===version){setState(value);setError("");}}).catch(()=>{if(alive)setError("Your latest activity could not be loaded. Refresh to try again.");});};const visible=()=>{if(document.visibilityState==="visible")refresh();};window.addEventListener("bynv:journey-changed",refresh);document.addEventListener("visibilitychange",visible);const timer=setInterval(visible,60000);return()=>{alive=false;clearInterval(timer);window.removeEventListener("bynv:journey-changed",refresh);document.removeEventListener("visibilitychange",visible);};},[]);
  const facts=momentumFacts(state),next=nextExperienceStep(state),cycle=state.cycle,days=cycle?cycleProgress(cycle.starts_on,cycle.ends_on,state.today):null;
  const steps=entrySteps(state.daily), stats=momentum(state.recent,state.today);
  const completedCycles=state.cycles.filter(c=>c.status==="completed"),completedGoals=state.goals.filter(g=>g.status==="completed");
  const milestones=[["Blueprint established",state.assessmentComplete],["First action completed",stats.actions>=1],["Seven useful actions",stats.actions>=7],["Three honest check-ins",state.recent.filter(e=>e.focus_date<=state.today&&(entryStatus(e)!==null||e.recovery)).length>=3],["First Cycle reviewed",completedCycles.length>=1],["First goal completed",completedGoals.length>=1],["First reassessment",state.assessmentChange!=null]] as const;
  return <div className="momentum-feed">
    {error&&<p role="alert">{error}</p>}
    <section className="command-kai"><KaiAvatar/><div><p className="eyebrow">Kai · Your next move</p><h2>{next.greeting}</h2><p>{next.message}</p><Link className="button" href={next.href}>{next.label}</Link></div></section>
    <div className="momentum-grid">
      <section className="command-panel"><p className="eyebrow">What you’re working on</p><h2>{cycle?.focus||"Choose what better means to you."}</h2>{cycle&&days?<><p>{cycle.success_vision||"Your chosen direction is saved."}</p><progress value={days.day} max={days.total} aria-label="Time through your Cycle"/><p>Day {days.day} of {days.total} · {days.reviewDue?"Ready to show the change":`Review on ${cycle.ends_on}`}</p>{cycle.personal_reward&&<p>Your reward: {cycle.personal_reward}</p>}</>:<p>Turn your own priority into a small 14-day plan.</p>}<Link className="command-link" href="/architect-cycle">{cycle?"Continue or review my Cycle":"Choose my direction"}</Link></section>
      <section className="command-panel"><p className="eyebrow">Today’s Plan</p><h2>{state.daily?.priority||"What matters today?"}</h2>{steps.length?<><p>{steps.filter(s=>s.done).length} of {steps.length} steps completed{entryStatus(state.daily)==="progress"?" · Made progress":""}</p><ul>{steps.map(step=><li key={step.id}>{step.done?"✓ ":"○ "}{step.text}</li>)}</ul></>:<p>No steps chosen yet. Your goal and Cycle are ready to help you choose.</p>}<Link className="command-link" href="/daily-focus">{entryStatus(state.daily)==="done"?"View today’s win":"Open Today’s Plan"}</Link></section>
    </div>
    <section className="command-momentum" aria-label="Momentum totals"><div><strong>{stats.actions}</strong><span>actions completed</span></div><div><strong>{stats.streak}</strong><span>day Build Streak</span></div><div><strong>{completedCycles.length}</strong><span>Cycles completed</span></div><div><strong>{completedGoals.length}</strong><span>goals completed</span></div></section>
    <p className="command-small muted">A Build Streak counts consecutive days with a completed step. A gap never erases earlier work. Today stays open in {state.timezone.replaceAll("_"," ")}.</p>
    {facts.recoveryNeeded.length>0&&<section className="command-panel"><p className="eyebrow">Recovery Check-In</p><h2>{facts.recoveryNeeded.length} {facts.recoveryNeeded.length===1?"commitment needs":"commitments need"} a next move.</h2><p>Missing a step doesn’t erase the goal. Tell Kai what got in the way, then keep it, shrink it, move it, or replace it.</p>{facts.recoveryNeeded.slice(0,3).map(entry=><article className="momentum-event" key={entry.id}><strong>{entry.priority||"Your saved commitment"}</strong><p>{entry.focus_date} · {entrySteps(entry).filter(s=>!s.done).map(s=>s.text).join("; ")}</p></article>)}<Link className="button" href="/daily-focus#recovery">Choose a recovery step</Link></section>}
    <section className="command-panel"><p className="eyebrow">Consistency includes honesty</p><h2>{facts.checkins} {facts.checkins===1?"check-in":"check-ins"} in the last seven days.</h2><div className="momentum-checkins">{Array.from({length:7},(_,i)=>addDays(state.today,i-6)).map(date=>{const entry=state.recent.find(e=>e.focus_date===date);const recorded=Boolean(entry&&(entryStatus(entry)!==null||entry.recovery));return <span key={date} className={recorded?"recorded":""} title={`${date}: ${recorded?"Checked in":"No check-in"}`}>{new Date(`${date}T12:00:00Z`).toLocaleDateString("en-US",{weekday:"short",timeZone:"UTC"})} {recorded?"✓":"—"}</span>;})}</div><p>Done, partial progress, and honest missed check-ins all count here. A gap doesn’t erase the work you’ve done.</p>{facts.comeback&&<p><strong>Architect milestone: you came back and completed a recovery action.</strong></p>}</section>
    <div className="momentum-grid"><section className="command-panel"><h2>What you actually did.</h2>{facts.completedActions.length?facts.completedActions.slice(0,6).map((action,i)=><article className="momentum-event" key={`${action.date}-${action.id}-${i}`}><strong>✓ {action.text}</strong><p>{action.date} · {action.priority}</p></article>):<p>Your first completed action will appear here.</p>}</section><section className="command-panel"><h2>Progress, even before it’s finished.</h2>{facts.progressDays.length?facts.progressDays.slice(0,4).map(entry=><article className="momentum-event" key={entry.id}><strong>{entry.priority||"Your daily action"}</strong><p>{entry.focus_date} · Made progress</p><p>{entry.reflection||"Partial progress recorded. Your unfinished steps still have a place."}</p></article>):<p>You can record Made progress on days when you move forward without finishing everything.</p>}{state.goals.filter(g=>g.advanced_at).slice(0,3).map(goal=><article className="momentum-event" key={goal.id}><strong>{goal.title}</strong><p>Progress recorded · {goal.advanced_at?.slice(0,10)}</p></article>)}</section></div>
    <details className="command-panel"><summary>Architect milestones</summary><ul className="milestone-list">{milestones.map(([label,earned])=><li key={label} className={earned?"earned":""}><span>{earned?"✓":"○"}</span><strong>{label}</strong><span>{earned?"Reached":"Ahead"}</span></li>)}</ul></details>
    {facts.dueGoals.length>0&&<section className="command-panel"><h2>Goals worth checking in on.</h2>{facts.dueGoals.map(goal=><p key={goal.id}>{goal.title} · Your chosen date: {goal.target_date}</p>)}<Link href="/goals">Review progress or adjust the date</Link></section>}
    {state.cycles.some(c=>c.change_review)||state.goals.some(g=>g.change_review || g.review_history?.length)?<section className="command-panel"><h2>What changed, in your words.</h2>{[...state.cycles.filter(c=>c.change_review).map(c=>({id:c.id,title:c.focus,review:c.change_review,history:c.review_history})),...state.goals.filter(g=>g.change_review || g.review_history?.length).map(g=>({id:g.id,title:g.title,review:g.change_review,history:g.review_history}))].slice(0,5).map(item=><article className="momentum-event" key={item.id}><h3>{item.title}</h3><ChangeEvidence review={item.review}/><ReviewHistory history={item.history} current={Boolean(item.review)}/></article>)}<p>Your reviews describe your experience. Activity totals and scores are separate evidence.</p></section>:null}
    {facts.recoveries.length>0&&<details className="command-panel"><summary>Recovery decisions you’ve kept</summary>{facts.recoveries.slice(0,8).map(entry=><article key={entry.id} className="momentum-event"><strong>{entry.priority}</strong><p>{entry.recovery?.reason||entry.recovery?.blocker||"A new approach chosen"} · {entry.recovery?.next_date}</p><p>{entry.recovery?.next_action}</p></article>)}</details>}
    <section className="command-panel"><p className="eyebrow">A useful tool for your direction</p><h2>Try one idea, then put it to work.</h2>{relevantResources(state).map(resource=><article className="momentum-event" key={resource.slug}><Link href={`/resources/${resource.slug}`}>{resource.title}</Link><p>{resource.summary} · {resource.tier === "free"?"Free":`${resource.tier} membership and above`}</p></article>)}<Link href="/resources">Explore the Architect Library</Link></section>
  </div>;
}
