"use client";
import { useState } from "react";
import { products } from "@/lib/data";
import { BYNV_CONTACT_EMAIL } from "@/lib/contact";
export function Shop() {
  const [selected, setSelected] = useState<number | null>(null);
  const product = selected === null ? null : products[selected];
  return <><div className="product-grid">{products.map((item, index) => <article className="product" key={item.name}><button className={`product-art product-art-${index}`} type="button" aria-label={`Preview ${item.name}`} onClick={() => setSelected(index)} /><p className="eyebrow">{item.category}</p><h2>{item.name}</h2><p>{item.description}</p><div><strong>{item.price}</strong><button type="button" onClick={() => setSelected(index)}>Preview item</button></div></article>)}</div>
    <div className="shop-disclosure"><h2>Product preview, before purchase.</h2><p>These images are BYNV concept mockups. Supplier, inventory, checkout, fulfillment, and delivery estimates are not connected, so no merchandise order or payment is accepted today.</p><p>Planned prices may change. Shipping will be calculated and charged separately where applicable. Final shipping regions and a clear return/refund policy will be published before any item becomes available to buy.</p><p>Merchandise questions: <a href={`mailto:${BYNV_CONTACT_EMAIL}`}>{BYNV_CONTACT_EMAIL}</a></p></div>
    {product && <div className="product-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setSelected(null); }}><section className="product-modal" role="dialog" aria-modal="true" aria-labelledby="product-preview-title"><button className="product-modal-close" type="button" aria-label="Close item preview" onClick={() => setSelected(null)}>×</button><div className={`product-art product-art-${selected}`} /><div><p className="eyebrow">Visual concept · {product.category}</p><h2 id="product-preview-title">{product.name}</h2><p>{product.description}</p><dl><div><dt>Planned price</dt><dd>{product.price}</dd></div><div><dt>Variants</dt><dd>{product.variants.join(" · ")}</dd></div><div><dt>Availability</dt><dd>{product.availability}</dd></div><div><dt>Shipping</dt><dd>Separate where applicable; regions and rates will be shown before purchase.</dd></div><div><dt>Returns</dt><dd>Final return and refund terms will be published before orders open.</dd></div></dl><button className="button secondary" type="button" disabled>Purchase unavailable</button></div></section></div>}
  </>;
}
