import { addDays, entryStatus, entrySteps, momentum, type Experience } from "./experience.ts";
export function nextExperienceStep(state: Experience) {
  const name = state.name.split(/\s+/)[0] || "Architect", stats = momentum(state.recent, state.today);
  if (!state.assessmentComplete) return { greeting: `Welcome, ${name}. Let’s find your starting point.`, message: "Your saved assessment is ready to continue. We’ll use it to build a plan that fits you.", href: "/architect-assessment", label: "Continue my assessment" };
  if (state.cycle && state.cycle.ends_on < state.today) return { greeting: `${name}, your Cycle is ready for a review.`, message: `You worked on “${state.cycle.focus}”. Let’s look at what changed and choose what to carry into the next two weeks.`, href: "/architect-cycle", label: "Review my Cycle" };
  if (state.unresolved.length) {
    const entry = state.unresolved[0], inactive = entry.focus_date < addDays(state.today, -2);
    return { greeting: inactive ? `Welcome back, ${name}. One small move is enough to restart.` : `${name}, let’s pick up the action still waiting.`, message: `${entryStatus(entry) === "missed" ? "You said it didn’t happen" : "There’s an unfinished action"} from ${entry.focus_date}: “${entrySteps(entry).find(s => !s.done)?.text}” Keep it, make it smaller, move it, or choose a different approach.`, href: "/daily-focus#recovery", label: "Choose my next move" };
  }
  if (entryStatus(state.daily) === "done") return { greeting: stats.actions === 1 ? `Your first action is complete, ${name}.` : `You followed through, ${name}.`, message: `${stats.thisWeek} ${stats.thisWeek === 1 ? "action" : "actions"} completed in the last seven days. You can call today complete. We’ll pick up your next step when you return.`, href: "/momentum", label: "See my momentum" };
  if (!state.daily?.recovery && (state.daily?.check_in === "missed" || state.daily?.check_in === "progress")) return { greeting: `${name}, let’s work with what happened.`, message: state.daily.check_in === "progress" ? "The progress you made counts. Choose what will make the remaining step realistic tomorrow." : "A missed action is information. Let’s decide what to keep, shrink, move, or replace.", href: "/daily-focus#recovery", label: "Adjust my next step" };
  if (state.daily?.recovery) return { greeting: `${name}, your next move is saved.`, message: `${state.daily.recovery.next_action} · Planned for ${state.daily.recovery.next_date}. Your original check-in stays in your history.`, href: "/daily-focus", label: "View my recovery plan" };
  const pendingStep = entrySteps(state.daily).find(step => !step.done);
  if (pendingStep) return { greeting: `${name}, here’s your next useful move.`, message: pendingStep.text, href: "/daily-focus", label: "Continue Today’s Plan" };
  const dueGoal = state.goals.find(goal => goal.status === "active" && goal.target_date && goal.target_date <= addDays(state.today, 3));
  if (dueGoal) return { greeting: `${name}, a goal is worth checking in on.`, message: `You chose ${dueGoal.target_date} for “${dueGoal.title}”. Review what moved, choose a small next step, or adjust that date.`, href: "/goals", label: "Review my goal" };
  if (state.assessmentChange != null && Math.abs(state.assessmentChange) >= 5 && state.assessmentDate && state.assessmentDate >= addDays(state.today, -1)) return { greeting: `${name}, your latest assessment has changed.`, message: `Your self-reported score moved ${state.assessmentChange > 0 ? "up" : "down"} ${Math.abs(state.assessmentChange)} points. Compare the areas and decide what this means for you.`, href: "/momentum#comparison", label: "Compare my assessments" };
  const lastActivity = state.recent.filter(e => e.focus_date <= state.today && (entryStatus(e) || e.recovery)).sort((a,b) => b.focus_date.localeCompare(a.focus_date))[0];
  if (lastActivity && lastActivity.focus_date < addDays(state.today,-3)) return { greeting: `Welcome back, ${name}. Your work is still here.`, message: "Choose one small move for today. You don’t have to restart or catch up on everything.", href: "/daily-focus", label: "Find one useful step" };
  if (state.cycle) return { greeting: `${name}, here’s your next useful move.`, message: `${entrySteps(state.daily)[0]?.text || state.cycle.plan_steps[0] || `Choose a small action that moves “${state.cycle.focus}” forward today.`}${state.cycle.ends_on <= addDays(state.today,2) ? " Your Cycle is nearly ready for a review of what changed." : ""}`, href: "/daily-focus", label: entrySteps(state.daily).length ? "Continue Today’s Plan" : "Choose today’s steps" };
  const completed = state.cycles.find(c => c.status === "completed");
  if (completed) return { greeting: `${name}, you finished an Architect Cycle.`, message: `You worked on “${completed.focus}”. Keep what helped, adjust what didn’t, and choose what you want to build next.`, href: "/architect-cycle", label: "Build my next Cycle" };
  const goal = state.goals.find(g => g.status === "active");
  if (goal) return { greeting: `${name}, let’s put your goal into action.`, message: `You chose “${goal.title}”. Build a small 14-day plan around it, using the progress you want to see.`, href: `/architect-cycle?goal=${encodeURIComponent(goal.id)}`, label: "Build a plan for my goal" };
  return { greeting: `${name}, your Blueprint is ready.`, message: "What would you genuinely like to be different? Choose your own direction. Your Blueprint can help if you want ideas.", href: state.orientationComplete ? "/architect-cycle" : "/orientation", label: state.orientationComplete ? "Choose my first priority" : "Show me how BYNV works" };
}
