-- Launch readiness: private owner/admin authority, first-party analytics,
-- First Circle feedback, database hardening, and supporting indexes.

create table if not exists public.account_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  platform_role text not null default 'member' check (platform_role in ('member', 'admin', 'owner')),
  entitlement_tier text check (entitlement_tier in ('foundation', 'builder', 'architect', 'architect_coaching', 'graduate')),
  entitlement_status text not null default 'active' check (entitlement_status in ('active', 'paused')),
  reason text check (char_length(reason) <= 500),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_events (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 1 and 120),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view','snapshot_start','snapshot_complete','signup_start','signup_complete','architect_assessment_start','architect_assessment_complete','blueprint_view','daily_active','membership_view','checkout_start','checkout_complete','cancellation','feedback_submit')),
  anonymous_id text check (anonymous_id is null or char_length(anonymous_id) between 10 and 80),
  user_id uuid references auth.users(id) on delete set null,
  route text not null check (char_length(route) between 1 and 300),
  metadata jsonb not null default '{}'::jsonb check (pg_column_size(metadata) <= 4096),
  created_at timestamptz not null default now()
);

create table if not exists public.first_circle_feedback (
  user_id uuid primary key references auth.users(id) on delete cascade,
  signup_easy integer check (signup_easy between 1 and 5),
  understood_bynv integer check (understood_bynv between 1 and 5),
  assessment_clear integer check (assessment_clear between 1 and 5),
  blueprint_useful integer check (blueprint_useful between 1 and 5),
  daily_direction_clear integer check (daily_direction_clear between 1 and 5),
  kai_helpful integer check (kai_helpful between 1 and 5),
  confused_by text check (char_length(confused_by) <= 3000),
  unnecessary text check (char_length(unnecessary) <= 3000),
  return_tomorrow text check (char_length(return_tomorrow) <= 3000),
  would_pay boolean,
  additional_feedback text check (char_length(additional_feedback) <= 5000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists analytics_events_type_date_idx on public.analytics_events(event_type, created_at desc);
create index if not exists analytics_events_user_date_idx on public.analytics_events(user_id, created_at desc) where user_id is not null;
create index if not exists admin_audit_events_date_idx on public.admin_audit_events(created_at desc);
create index if not exists architect_blueprints_assessment_idx on public.architect_blueprints(assessment_id);
create index if not exists architect_invitations_accepted_by_idx on public.architect_invitations(accepted_by);
create index if not exists architect_invitations_created_by_idx on public.architect_invitations(created_by);
create index if not exists community_comment_reactions_user_idx on public.community_comment_reactions(user_id);
create index if not exists community_comments_parent_idx on public.community_comments(parent_comment_id);
create index if not exists community_comments_user_idx on public.community_comments(user_id);
create index if not exists community_member_restrictions_created_by_idx on public.community_member_restrictions(created_by);
create index if not exists community_moderation_actions_moderator_idx on public.community_moderation_actions(moderator_user_id);
create index if not exists community_moderation_actions_report_idx on public.community_moderation_actions(report_id);
create index if not exists community_post_reactions_user_idx on public.community_post_reactions(user_id);
create index if not exists community_posts_user_idx on public.community_posts(user_id);
create index if not exists community_reports_reporter_idx on public.community_reports(reporter_user_id);
create index if not exists email_events_user_idx on public.email_events(user_id);
create index if not exists kai_messages_user_idx on public.kai_messages(user_id);

alter table public.account_access enable row level security;
alter table public.admin_audit_events enable row level security;
alter table public.analytics_events enable row level security;
alter table public.first_circle_feedback enable row level security;

revoke all on public.account_access, public.admin_audit_events, public.analytics_events from anon, authenticated;
grant usage, select on sequence public.analytics_events_id_seq to service_role;

drop policy if exists "Members read own First Circle feedback" on public.first_circle_feedback;
create policy "Members read own First Circle feedback" on public.first_circle_feedback for select to authenticated using (user_id = (select auth.uid()));
drop policy if exists "Members create own First Circle feedback" on public.first_circle_feedback;
create policy "Members create own First Circle feedback" on public.first_circle_feedback for insert to authenticated with check (user_id = (select auth.uid()));
drop policy if exists "Members update own First Circle feedback" on public.first_circle_feedback;
create policy "Members update own First Circle feedback" on public.first_circle_feedback for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
grant select, insert, update on public.first_circle_feedback to authenticated;

alter function public.set_updated_at() set search_path = '';
alter function public.community_access_rank(text) set search_path = '';

revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.rls_auto_enable() from public, anon, authenticated;
revoke all on function public.can_access_community_room(uuid) from public, anon;
revoke all on function public.is_community_admin() from public, anon;
revoke all on function public.is_community_moderator() from public, anon;
revoke all on function public.is_community_restricted(uuid) from public, anon;
grant execute on function public.can_access_community_room(uuid) to authenticated;
grant execute on function public.is_community_admin() to authenticated;
grant execute on function public.is_community_moderator() to authenticated;
grant execute on function public.is_community_restricted(uuid) to authenticated;

drop trigger if exists set_updated_at on public.account_access;
create trigger set_updated_at before update on public.account_access for each row execute procedure public.set_updated_at();
drop trigger if exists set_updated_at on public.first_circle_feedback;
create trigger set_updated_at before update on public.first_circle_feedback for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name) values (new.id, nullif(trim(coalesce(new.raw_user_meta_data ->> 'display_name', '')), '')) on conflict (id) do nothing;
  insert into public.memberships (user_id) values (new.id) on conflict (user_id) do nothing;
  insert into public.community_entitlements (user_id) values (new.id) on conflict (user_id) do nothing;
  insert into public.account_access (user_id) values (new.id) on conflict (user_id) do nothing;
  return new;
end;
$$;
revoke all on function public.handle_new_user() from public, anon, authenticated;

insert into public.account_access (user_id)
select id from auth.users on conflict (user_id) do nothing;

-- Keep privileged policy helpers outside the exposed API schema. Public wrappers
-- are invoker functions and disclose only a yes/no answer for the current JWT.
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create or replace function private.is_community_admin()
returns boolean language sql security definer stable set search_path = '' as $$
  select exists (select 1 from public.community_entitlements where user_id = (select auth.uid()) and community_role = 'admin')
$$;
create or replace function private.is_community_moderator()
returns boolean language sql security definer stable set search_path = '' as $$
  select exists (select 1 from public.community_entitlements where user_id = (select auth.uid()) and community_role in ('moderator', 'admin'))
$$;
create or replace function private.is_community_restricted(target_user_id uuid)
returns boolean language sql security definer stable set search_path = '' as $$
  select exists (select 1 from public.community_member_restrictions where user_id = target_user_id and (restricted_until is null or restricted_until > now()))
$$;
create or replace function private.can_access_community_room(target_room_id uuid)
returns boolean language sql security definer stable set search_path = '' as $$
  select exists (
    select 1 from public.community_rooms room
    left join public.community_entitlements entitlement on entitlement.user_id = (select auth.uid())
    where room.id = target_room_id and room.active
      and (
        room.access_level = 'community'
        or (room.access_level = 'first_circle' and coalesce(entitlement.first_circle, false))
        or (room.access_level = 'priority' and coalesce(entitlement.access_level, 'community') in ('priority', 'mastermind'))
        or (room.access_level = 'mastermind' and coalesce(entitlement.access_level, 'community') = 'mastermind')
      )
  )
$$;

revoke all on all functions in schema private from public, anon;
grant execute on function private.is_community_admin(), private.is_community_moderator(), private.is_community_restricted(uuid), private.can_access_community_room(uuid) to authenticated;

create or replace function public.is_community_admin()
returns boolean language sql security invoker stable set search_path = '' as $$ select private.is_community_admin() $$;
create or replace function public.is_community_moderator()
returns boolean language sql security invoker stable set search_path = '' as $$ select private.is_community_moderator() $$;
create or replace function public.is_community_restricted(target_user_id uuid)
returns boolean language sql security invoker stable set search_path = '' as $$ select private.is_community_restricted(target_user_id) $$;
create or replace function public.can_access_community_room(target_room_id uuid)
returns boolean language sql security invoker stable set search_path = '' as $$ select private.can_access_community_room(target_room_id) $$;

revoke all on function public.is_community_admin(), public.is_community_moderator(), public.is_community_restricted(uuid), public.can_access_community_room(uuid) from public, anon;
grant execute on function public.is_community_admin(), public.is_community_moderator(), public.is_community_restricted(uuid), public.can_access_community_room(uuid) to authenticated;

drop policy if exists "Service-only account access" on public.account_access;
create policy "Service-only account access" on public.account_access for all to anon, authenticated using (false) with check (false);
drop policy if exists "Service-only admin audit" on public.admin_audit_events;
create policy "Service-only admin audit" on public.admin_audit_events for all to anon, authenticated using (false) with check (false);
drop policy if exists "Service-only analytics" on public.analytics_events;
create policy "Service-only analytics" on public.analytics_events for all to anon, authenticated using (false) with check (false);
